[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[project]
name = "hyperanf"
version = "0.1.0"
authors = [
  { name="Nick Cui", email="lening.n.cui@vanderbilt.edu" },
]
description = "HyperANF implementation in Python"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/dnxjcui/hyperanf"
Issues = "https://github.com/dnxjcui/hyperanf/issues"